# Generated by Django 2.2 on 2019-04-29 13:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_auto_20190429_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(1)]),
        ),
    ]
