# Generated by Django 2.2 on 2019-04-29 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_auto_20190429_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
