# Generated by Django 2.2 on 2019-04-29 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_auto_20190429_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='jobposition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='employees.JobPosition'),
        ),
    ]
