# Generated by Django 2.2 on 2019-04-30 12:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_auto_20190430_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.BigIntegerField(validators=[django.core.validators.RegexValidator(regex='^\\d{9,15}$')]),
        ),
    ]
